### ISSUE TITLE
MRST_Shale results not matching reference solutions

### ISSUE THREAD

**Issue by mszulcz** [BinWang0213/MRST_Shale#2]
Dear Mr. Wang,

I recently installed MRST_Shale and ran all of the example cases.  For Case 1 and Case 4, the MRST_Shale results for gas production rate do not match the reference solution.  I've tried to attached pictures of the gas production plots to show the comparisons.  Are the results supposed to match for the cases?  If so, do you know why they aren't?

Thank you for your time.

![Case1_MRST_EDFM_benchmark_GasProductionRate](https://user-images.githubusercontent.com/43887325/106166134-da74bf80-6159-11eb-8a4a-77e3fde95a8d.jpg)
![Case4_NaturalFrac_Geomechanics_Barnett_GasProductionRate](https://user-images.githubusercontent.com/43887325/106166154-df397380-6159-11eb-9002-81ba57c22c11.jpg)

**Comment by BinWang0213** [comment]
Hi,

To match the reference solution, you need to check the following things in these two cases:

- Grid setup (typically finer mesh gives better match)
- Fracture permeability (EDFM can not handle low perm fracture, k_frac<5-10*Darcy)
- Using the same grid in CMG (Case1)

For example, in `Case1_MRST_LGR_benchmark.m`
To match the reference solution of LGR250.csv that uses `k_frac = 10*Darcy`, you need to

`[perm_rock,perm_frac]=deal(0.0005*milli*darcy,0.5*darcy);` @ Line 48
by
`[perm_rock,perm_frac]=deal(0.0005*milli*darcy,10*darcy);`

And uncomment `data_file='LGR250.csv';` @ Line 106

Now. you will get the matched results for cumulative production:
![image](https://user-images.githubusercontent.com/20053787/106667257-50b85e00-656e-11eb-8dab-7613124722c4.png)
